#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
  if command -v udevadm >/dev/null 2>&1; then
    udevadm control --reload-rules || true
  fi
  if command -v update-initramfs >/dev/null 2>&1; then
    update-initramfs -u || true
  fi
fi
exit 0
